@obj = Objective.create(title: 'Colorful DIVs', category: 'Todo' )
@obj = Objective.create(title: 'HAML practice', category: 'Todo' )
@obj = Objective.create(title: 'Javascript to change text button', category: 'Todo' )
@obj = Objective.create(title: 'JQuery', category: 'Todo' )
@obj = Objective.create(title: 'Nav bar', category: 'Todo' )
@obj = Objective.create(title: 'Devise user', category: 'Todo' )
@obj = Objective.create(title: 'Create Ruby class with attr_accessor', category: 'Todo' )
@obj = Objective.create(title: 'Bootstrap', category: 'Todo' )
@obj = Objective.create(title: 'Sort by Date', category: 'Todo' )
@obj = Objective.create(title: 'Sort by Ascending', category: 'Todo' )
@obj = Objective.create(title: 'Import/Export Todo List', category: 'Todo' )
@obj = Objective.create(title: 'GitHub', category: 'Todo' )
@obj = Objective.create(title: 'Heroku', category: 'Todo' )
@obj = Objective.create(title: 'Articulo es indisponible', category: 'Todo' )
@obj = Objective.create(title: 'content_for', category: 'Todo' )


@obj = Objective.create(title: 'Fresh Vegetable', category: 'Bass' )
@obj = Objective.create(title: 'Sorry', category: 'Bass' )
@obj = Objective.create(title: 'Modern Girl', category: 'Bass’' )
@obj = Objective.create(title: 'Shine Eye Girl', category: 'Bass' )
@obj = Objective.create(title: 'Don’t You Worry', category: 'Bass' )
@obj = Objective.create(title: 'Other Side', category: 'Bass' )
@obj = Objective.create(title: 'Seeking the Lost', category: 'Bass' )
@obj = Objective.create(title: 'Michael Jackson-Want You Back', category: 'Bass' )
@obj = Objective.create(title: 'Don’t Look Back', category: 'Bass' )
@obj = Objective.create(title: 'Green Day', category: 'Bass' )
@obj = Objective.create(title: 'I Really Like You', category: 'Bass' )
@obj = Objective.create(title: 'Another One Bites The Dust', category: 'Bass' )
@obj = Objective.create(title: 'Don’t Look Any Further', category: 'Bass' )
@obj = Objective.create(title: 'Axwell-Ingrosso - Something New', category: 'Bass' )


@obj = Objective.create(title: 'Fmaj to A/F', category: 'Guitar' )
@obj = Objective.create(title: 'Palm Muting', category: 'Guitar' )

@obj = Objective.create(title: 'Hard To Say I’m Sorry', category: 'Piano' )
@obj = Objective.create(title: 'Travis - Window', category: 'Piano' )

@obj = Objective.create(title: 'Basic Rock Beat with 16th note Hi Hats', category: 'Drums' )
@obj = Objective.create(title: 'Basic Rock Beat with 8th note Hi Hats', category: 'Drums' )
